const test=require("node:test");const assert=require("node:assert/strict");const rules=require("../src/games/poker-night/rules");const evalr=require("../src/games/poker-night/evaluator");
function room(count=3,settings={mode:"holdem",tableMode:"cash",buyIn:1000}){const players=Array.from({length:count},(_,i)=>({id:`p${i+1}`,name:`玩家${i+1}`,connected:true}));const r={hostId:"p1",players,settings,game:null};r.game=rules.createGame(players,settings,()=>.42,1000);return r;}
test("牌型比较识别皇家同花顺高于四条",()=>{const royal=evalr.evaluateFive(["Ah","Kh","Qh","Jh","Th"]),quads=evalr.evaluateFive(["Ac","Ad","Ah","As","2c"]);assert.equal(royal.name,"皇家同花顺");assert.ok(evalr.compare(royal.score,quads.score)>0)});
test("奥马哈必须正好使用两张底牌和三张公共牌",()=>{const result=evalr.bestOmaha(["Ah","Kh","2c","3d"],["Qh","Jh","Th","9h","8h"]);assert.equal(result.name,"皇家同花顺");assert.equal(result.cards.filter(c=>["Ah","Kh","2c","3d"].includes(c)).length,2)});
test("德州发两张、奥马哈发四张且底牌只对本人公开",()=>{const h=room(3);assert.ok(h.players.every(p=>p.hole.length===2));const other=rules.publicRoom(h,"p1").players.find(p=>p.id==="p2");assert.ok(other.hole.every(c=>c===null));const o=room(3,{mode:"omaha",buyIn:1000});assert.ok(o.players.every(p=>p.hole.length===4));assert.equal(o.game.handType,"omaha")});
test("混合桌逐手交替德州与PLO",()=>{const r=room(2,{mode:"mixed",buyIn:1000});assert.equal(r.game.handType,"holdem");r.game.street="showdown";r.game.deadline=0;rules.tick(r,1);assert.equal(r.game.handType,"omaha")});
test("行动限时30秒且延时卡消耗后增加30秒",()=>{const r=room(2);const p=r.players[r.game.actorIndex],before=r.game.deadline;assert.equal(before,31000);rules.useTimeCard(r,p.id);assert.equal(p.timeCards,4);assert.equal(r.game.deadline,before+30000)});
test("弃牌立即发放底池但底牌默认保密，可自愿只亮一张",()=>{const r=room(2);const actor=r.players[r.game.actorIndex],winner=r.players.find(p=>p.id!==actor.id),before=winner.chips;rules.act(r,actor.id,{type:"fold"},2000);assert.equal(r.game.street,"showdown");assert.equal(r.game.showdown.reason,"fold");assert.ok(winner.chips>before);const beforeReveal=rules.publicRoom(r,actor.id).players.find(p=>p.id===winner.id);assert.deepEqual(beforeReveal.hole,[null,null]);rules.revealCards(r,winner.id,{index:0});const afterReveal=rules.publicRoom(r,actor.id).players.find(p=>p.id===winner.id);assert.equal(afterReveal.hole[0],winner.hole[0]);assert.equal(afterReveal.hole[1],null)});
test("一人全下后仍等待另一位玩家行动才发完公共牌摊牌",()=>{const r=room(2);const firstIndex=r.game.actorIndex,first=r.players[firstIndex],second=r.players.find(p=>p.id!==first.id);rules.act(r,first.id,{type:"allin"},2000);assert.equal(r.game.street,"preflop");assert.equal(r.game.board.length,0);assert.equal(r.players[r.game.actorIndex].id,second.id);rules.act(r,second.id,{type:"call"},3000);assert.equal(r.game.street,"showdown");assert.equal(r.game.showdown.reason,"cards");assert.equal(r.game.board.length,5);const publicView=rules.publicRoom(r,first.id).players.find(p=>p.id===second.id);assert.ok(publicView.hole.every(Boolean))});
test("补码由房主决定数量并恢复五张延时卡",()=>{const r=room(2);r.players[1].timeCards=0;rules.requestRebuy(r,"p2");assert.equal(r.players[1].rebuyRequest,true);assert.throws(()=>rules.approveRebuy(r,"p2",{playerId:"p2",amount:300}),/只有房主/);const before=r.players[1].chips;rules.approveRebuy(r,"p1",{playerId:"p2",amount:300});assert.equal(r.players[1].chips,before+300);assert.equal(r.players[1].timeCards,5)});
test("房主可在开局前设置模式和带入",()=>{const r={hostId:"p1",players:[],game:null,settings:{}};rules.configure(r,"p1",{mode:"mixed",tableMode:"cash",buyIn:2500});assert.deepEqual(r.settings,{mode:"mixed",tableMode:"cash",buyIn:2500});assert.throws(()=>rules.configure(r,"p2",{mode:"holdem",tableMode:"cash",buyIn:1000}),/只有房主/)});
test("房主选择SNG后固定为无限注德州且所有玩家等额开局",()=>{const pending={hostId:"p1",players:[],game:null,settings:{}};rules.configure(pending,"p1",{mode:"omaha",tableMode:"sng",buyIn:1500});assert.deepEqual(pending.settings,{mode:"holdem",tableMode:"sng",buyIn:1500});const r=room(4,pending.settings);assert.equal(r.game.tableMode,"sng");assert.ok(r.players.every(p=>p.chips<=1500));assert.equal(r.game.handType,"holdem")});
test("SNG每五手提升一级盲注",()=>{const r=room(3,{mode:"holdem",tableMode:"sng",buyIn:1000});assert.equal(r.game.smallBlind,5);assert.equal(r.game.bigBlind,10);r.game.handNumber=5;r.game.street="showdown";r.game.deadline=0;rules.tick(r,1);assert.equal(r.game.handNumber,6);assert.equal(r.game.blindLevel,2);assert.equal(r.game.smallBlind,10);assert.equal(r.game.bigBlind,20)});
test("SNG禁止补码并在仅剩一人时公布冠军",()=>{const r=room(3,{mode:"holdem",tableMode:"sng",buyIn:1000});assert.throws(()=>rules.requestRebuy(r,"p2"),/不能补码/);r.players[1].chips=0;r.players[2].chips=0;rules.startHand(r,5000);assert.equal(r.game.status,"finished");assert.equal(r.game.street,"tournament-end");assert.equal(r.game.tournamentWinner.id,"p1");assert.equal(r.players[1].eliminated,true)});
test("当前玩家断线只保留十秒，避免整桌永久卡住",()=>{const r=room(2),p=r.players[r.game.actorIndex];rules.handleDisconnect(r,p,5000);assert.equal(r.game.deadline,15000);assert.match(p.lastAction,/保留10秒/);rules.tick(r,15000);assert.notEqual(r.game.actorIndex,r.players.indexOf(p));});
test("当前玩家及时重连后至少恢复十五秒操作时间",()=>{const r=room(2),p=r.players[r.game.actorIndex];p.timeCards=1;rules.handleDisconnect(r,p,5000);rules.handleReconnect(r,p,9000);assert.equal(r.game.deadline,24000);assert.equal(p.timeCards,5);assert.match(p.lastAction,/已重连/);});
