const test=require("node:test");const assert=require("node:assert/strict");const rules=require("../src/games/poker-night/rules");const evalr=require("../src/games/poker-night/evaluator");
function room(count=3,settings={mode:"holdem",buyIn:1000}){const players=Array.from({length:count},(_,i)=>({id:`p${i+1}`,name:`玩家${i+1}`,connected:true}));const r={hostId:"p1",players,settings,game:null};r.game=rules.createGame(players,settings,()=>.42,1000);return r;}
test("牌型比较识别皇家同花顺高于四条",()=>{const royal=evalr.evaluateFive(["Ah","Kh","Qh","Jh","Th"]),quads=evalr.evaluateFive(["Ac","Ad","Ah","As","2c"]);assert.equal(royal.name,"皇家同花顺");assert.ok(evalr.compare(royal.score,quads.score)>0)});
test("奥马哈必须正好使用两张底牌和三张公共牌",()=>{const result=evalr.bestOmaha(["Ah","Kh","2c","3d"],["Qh","Jh","Th","9h","8h"]);assert.equal(result.name,"皇家同花顺");assert.equal(result.cards.filter(c=>["Ah","Kh","2c","3d"].includes(c)).length,2)});
test("德州发两张、奥马哈发四张且底牌只对本人公开",()=>{const h=room(3);assert.ok(h.players.every(p=>p.hole.length===2));const other=rules.publicRoom(h,"p1").players.find(p=>p.id==="p2");assert.ok(other.hole.every(c=>c===null));const o=room(3,{mode:"omaha",buyIn:1000});assert.ok(o.players.every(p=>p.hole.length===4));assert.equal(o.game.handType,"omaha")});
test("混合桌逐手交替德州与PLO",()=>{const r=room(2,{mode:"mixed",buyIn:1000});assert.equal(r.game.handType,"holdem");r.game.street="showdown";r.game.deadline=0;rules.tick(r,1);assert.equal(r.game.handType,"omaha")});
test("行动限时30秒且延时卡消耗后增加30秒",()=>{const r=room(2);const p=r.players[r.game.actorIndex],before=r.game.deadline;assert.equal(before,31000);rules.useTimeCard(r,p.id);assert.equal(p.timeCards,4);assert.equal(r.game.deadline,before+30000)});
test("弃牌立即把底池发给唯一剩余玩家",()=>{const r=room(2);const actor=r.players[r.game.actorIndex],winner=r.players.find(p=>p.id!==actor.id),before=winner.chips;rules.act(r,actor.id,{type:"fold"},2000);assert.equal(r.game.street,"showdown");assert.ok(winner.chips>before)});
test("补码由房主决定数量并恢复五张延时卡",()=>{const r=room(2);r.players[1].timeCards=0;rules.requestRebuy(r,"p2");assert.equal(r.players[1].rebuyRequest,true);assert.throws(()=>rules.approveRebuy(r,"p2",{playerId:"p2",amount:300}),/只有房主/);const before=r.players[1].chips;rules.approveRebuy(r,"p1",{playerId:"p2",amount:300});assert.equal(r.players[1].chips,before+300);assert.equal(r.players[1].timeCards,5)});
test("房主可在开局前设置模式和带入",()=>{const r={hostId:"p1",players:[],game:null,settings:{}};rules.configure(r,"p1",{mode:"mixed",buyIn:2500});assert.deepEqual(r.settings,{mode:"mixed",buyIn:2500});assert.throws(()=>rules.configure(r,"p2",{mode:"holdem",buyIn:1000}),/只有房主/)});
