const {INVESTIGATORS,LOCATIONS,PLAYER_CARDS,ENEMIES,TREACHERIES}=require("./data");
const pick=a=>a[Math.floor(Math.random()*a.length)],clone=x=>JSON.parse(JSON.stringify(x));
const CHAOS={story:[1,0,0,-1,-1,-2,-2,-3,"skull","cultist","tentacle"],grim:[0,0,-1,-1,-2,-2,-3,-3,-4,"skull","cultist","tentacle"]};
function defaults(){return {difficulty:"story",choices:{}};}
function configure(room,id,p={}){if(p.investigator){if(!INVESTIGATORS.some(x=>x.id===p.investigator))throw Error("未知调查员");room.settings.choices[id]=p.investigator;return;}if(room.hostId!==id)throw Error("只有房主可以调整难度");if(!CHAOS[p.difficulty])throw Error("未知难度");room.settings.difficulty=p.difficulty;}
function deck(){return Array.from({length:6},()=>PLAYER_CARDS).flat().map((x,i)=>({...x,uid:`c${i}-${Math.random().toString(36).slice(2,6)}`})).sort(()=>Math.random()-.5);}
function createGame(players,settings={}){
 const used=new Set(),d=deck();const investigators=players.map((p,i)=>{let base=INVESTIGATORS.find(x=>x.id===settings.choices?.[p.id]);if(!base||used.has(base.id))base=INVESTIGATORS.find(x=>!used.has(x.id));used.add(base.id);return {...clone(base),playerId:p.id,playerName:p.name,maxHealth:base.health,maxSanity:base.sanity,damage:0,horror:0,resources:5,clues:0,location:"foyer",actions:3,hand:d.splice(0,5),deck:d.splice(0,5),assets:[],engaged:[],ended:false,abilityReady:true,firstInvestigate:true,firstFight:true};});
 const locations=Object.fromEntries(Object.entries(LOCATIONS).map(([id,x])=>[id,{...clone(x),clues:x.clues*players.length,revealed:["foyer","study","garden"].includes(id)}]));
 return {status:"playing",phase:"investigation",round:1,difficulty:settings.difficulty||"story",investigators,locations,enemies:[],leadIndex:0,currentIndex:0,act:1,actClues:[0,2,3,4][1]*players.length,agenda:1,doom:0,doomThreshold:[0,4,5,6][1],encounterCount:0,eventSeq:1,lastEvent:{type:"opening",title:"午夜档案",detail:"黑荆宅邸的大门在你们身后自行锁上。"},story:"三名失踪者留下同一地址：黑荆宅邸。午夜之前，找出塔楼隐藏的真相。",log:["案件开始：雨夜，黑荆宅邸。"]};
}
function inv(g,id){const x=g.investigators.find(x=>x.playerId===id);if(!x)throw Error("你不是本案调查员");if(g.status!=="playing")throw Error("案件已经结束");return x;}
function active(g,id){const x=inv(g,id);if(g.phase!=="investigation"||g.investigators[g.currentIndex]?.playerId!==id||x.ended)throw Error("现在不是你的行动阶段");if(x.actions<=0)throw Error("行动次数已经用完");return x;}
function emit(g,type,title,detail){g.eventSeq++;g.lastEvent={type,title,detail};g.log.unshift(detail||title);g.log=g.log.slice(0,16);}
function stat(i,name){return i[name]+i.assets.filter(x=>x.stat===name).reduce((n,x)=>n+x.bonus,0);}
function token(g,i){let t=pick(CHAOS[g.difficulty]);if(t==="tentacle"&&i.id==="professor"&&i.abilityReady){i.abilityReady=false;t=-2;}const mod=typeof t==="number"?t:t==="skull"?-g.agenda:t==="cultist"?-(1+Math.floor(g.doom/2)):-99;return {token:t,mod};}
function testSkill(g,i,name,difficulty,bonus=0){const t=token(g,i),total=stat(i,name)+bonus+t.mod;return {...t,total,success:t.token!=="tentacle"&&total>=difficulty};}
function spendAction(i){i.actions--;}
function opportunity(g,i){for(const uid of i.engaged){const e=g.enemies.find(x=>x.uid===uid&&!x.exhausted);if(e)hurt(g,i,e.damage,e.horror,`${e.name}发动趁虚攻击`);if(g.status!=="playing")return false;}return !i.defeated;}
function move(room,id,p){const g=room.game,i=active(g,id),from=g.locations[i.location],to=g.locations[p.location];if(!to||!from.connections.includes(to.id))throw Error("地点并不相连");if(to.lockedAct&&g.act<to.lockedAct)throw Error("这个地点尚未解锁");if(i.engaged.length)throw Error("与敌人交战时不能直接移动");spendAction(i);i.location=to.id;to.revealed=true;emit(g,"move",`${i.playerName}进入${to.name}`,to.text);afterAction(g);}
function investigate(room,id){const g=room.game,i=active(g,id),loc=g.locations[i.location];if(loc.clues<=0)throw Error("这里已经没有线索");spendAction(i);if(!opportunity(g,i))return;const bonus=i.id==="detective"&&i.firstInvestigate?1:0;i.firstInvestigate=false;const r=testSkill(g,i,"intellect",loc.shroud,bonus);if(r.success){loc.clues--;i.clues++;emit(g,"clue",`发现线索 · ${showToken(r.token)}`,`${i.playerName}在${loc.name}取得1条线索。`);}else emit(g,"fail",`调查失败 · ${showToken(r.token)}`,`技能值${r.total}，未达到隐蔽值${loc.shroud}。`);advanceAct(g);afterAction(g);}
function targetEnemy(g,i,uid){return g.enemies.find(e=>e.uid===uid&&(e.location===i.location||i.engaged.includes(uid)));}
function fight(room,id,p){const g=room.game,i=active(g,id),e=targetEnemy(g,i,p.enemyId);if(!e)throw Error("敌人不在这里");spendAction(i);const r=testSkill(g,i,"combat",e.fight);if(r.success){let dmg=1+i.assets.some(x=>x.damage?true:false)+(i.id==="veteran"&&i.firstFight?1:0);i.firstFight=false;e.health-=dmg;emit(g,"fight",`攻击命中 · ${showToken(r.token)}`,`${e.name}受到${dmg}点伤害。`);if(e.health<=0){g.enemies=g.enemies.filter(x=>x.uid!==e.uid);g.investigators.forEach(x=>x.engaged=x.engaged.filter(y=>y!==e.uid));emit(g,"enemy-defeated",`${e.name}被击败`,"空气中只剩潮湿的灰烬。");}}else emit(g,"fail",`攻击落空 · ${showToken(r.token)}`,`${i.playerName}没有击中${e.name}。`);afterAction(g);}
function evade(room,id,p){const g=room.game,i=active(g,id),e=targetEnemy(g,i,p.enemyId);if(!e)throw Error("敌人不在这里");spendAction(i);const r=testSkill(g,i,"agility",e.evade);if(r.success){e.exhausted=true;i.engaged=i.engaged.filter(x=>x!==e.uid);emit(g,"evade",`成功闪避 · ${showToken(r.token)}`,`${e.name}失去目标。`);}else emit(g,"fail",`闪避失败 · ${showToken(r.token)}`,`${e.name}仍紧紧跟着你。`);afterAction(g);}
function drawCard(i){if(!i.deck.length)i.deck=deck().slice(0,5);i.hand.push(i.deck.shift());}
function basic(room,id,p){const g=room.game,i=active(g,id);if(!["draw","resource"].includes(p.kind))throw Error("未知行动");spendAction(i);if(!opportunity(g,i))return;if(p.kind==="draw")drawCard(i);else i.resources++;emit(g,"basic",p.kind==="draw"?"翻阅随身物品":"整理补给",p.kind==="draw"?`${i.playerName}抽取1张牌。`:`${i.playerName}获得1资源。`);afterAction(g);}
function play(room,id,p){const g=room.game,i=active(g,id),idx=i.hand.findIndex(x=>x.uid===p.cardId),card=i.hand[idx];if(!card)throw Error("手中没有这张牌");if(i.resources<card.cost)throw Error("资源不足");spendAction(i);if(!opportunity(g,i))return;i.resources-=card.cost;i.hand.splice(idx,1);if(card.type==="asset"){i.assets.push(card);if(card.health)i.maxHealth+=card.health;}else if(card.event==="clue"){const loc=g.locations[i.location];if(loc.clues>0){loc.clues--;i.clues++;advanceAct(g);}}else if(card.event==="heal")i.damage=Math.max(0,i.damage-2);else if(card.event==="sanity")i.horror=Math.max(0,i.horror-2);emit(g,"card",`${i.playerName}打出「${card.name}」`,card.text);afterAction(g);}
function ability(room,id,p={}){const g=room.game,i=active(g,id);if(i.id!=="doctor"||!i.abilityReady)throw Error("当前没有可发动的行动能力");const target=g.investigators.find(x=>x.playerId===(p.targetId||id)&&x.location===i.location);if(!target)throw Error("目标必须在同一地点");i.abilityReady=false;spendAction(i);if(!opportunity(g,i))return;target.damage=Math.max(0,target.damage-1);emit(g,"heal",`${i.playerName}进行紧急处理`,`${target.playerName}恢复1点生命。`);afterAction(g);}
function endTurn(room,id){const g=room.game,i=active(g,id);i.actions=0;i.ended=true;emit(g,"turn",`${i.playerName}结束行动`,"调查权交给下一位尚未行动的队友。");nextInvestigator(g);}
function afterAction(g){if(g.status!=="playing")return;const i=g.investigators[g.currentIndex];if(i.actions<=0){i.ended=true;nextInvestigator(g);}}
function nextInvestigator(g){for(let step=1;step<=g.investigators.length;step++){const next=(g.currentIndex+step)%g.investigators.length;if(!g.investigators[next].ended){g.currentIndex=next;return;}}enemyPhase(g);}
function hurt(g,i,d,h,source){i.damage+=d;i.horror+=h;emit(g,"hurt",source,`${i.playerName}受到${d}点伤害和${h}点恐惧。`);if(i.damage>=i.maxHealth||i.horror>=i.maxSanity){i.defeated=true;i.ended=true;emit(g,"defeated",`${i.playerName}被击倒`,"这名调查员无法继续参与本案。");}if(g.investigators.every(x=>x.defeated))finish(g,false,"所有调查员都消失在宅邸中。");}
function enemyPhase(g){g.phase="enemy";for(const e of [...g.enemies]){if(e.exhausted){e.exhausted=false;continue;}let target=g.investigators.find(i=>!i.defeated&&i.location===e.location);if(!target&&e.hunter){const candidates=g.investigators.filter(i=>!i.defeated);if(candidates.length){e.location=candidates[0].location;target=candidates[0];}}if(target){if(!target.engaged.includes(e.uid))target.engaged.push(e.uid);hurt(g,target,e.damage,e.horror,`${e.name}发动袭击`);if(g.status!=="playing")return;}}upkeep(g);}
function upkeep(g){g.phase="upkeep";for(const i of g.investigators){if(i.defeated)continue;i.resources++;drawCard(i);}mythos(g);}
function encounter(g,i){const enemy=Math.random()<.46;if(enemy){const b=clone(pick(ENEMIES));b.uid=`e${++g.encounterCount}`;b.maxHealth=b.health+Math.max(0,g.investigators.length-1);b.health=b.maxHealth;b.location=i.location;b.exhausted=false;g.enemies.push(b);i.engaged.push(b.uid);emit(g,"spawn",`${b.name}现身`,`${b.name}与${i.playerName}交战。`);}else{const c=pick(TREACHERIES),r=testSkill(g,i,c.stat,c.difficulty);if(r.success)emit(g,"treachery",`${c.name} · 抵抗成功`,`${showToken(r.token)}：${i.playerName}挺过了神话侵袭。`);else hurt(g,i,c.damage,c.horror,`${c.name} · ${showToken(r.token)}`);}}
function mythos(g){g.phase="mythos";g.doom++;emit(g,"doom","厄运增长",`当前厄运 ${g.doom}/${g.doomThreshold}。`);if(g.doom>=g.doomThreshold){g.agenda++;g.doom=0;if(g.agenda>3)return finish(g,false,"月亮在无窗塔楼上方睁开了眼睛。仪式完成了。");g.doomThreshold=[0,4,5,6][g.agenda];emit(g,"agenda",`密谋推进至第${g.agenda}幕`,g.agenda===2?"宅邸开始吞噬自己的房间。":"塔楼中的钟声敲响了十三次。");}for(const i of g.investigators)if(!i.defeated){encounter(g,i);if(g.status!=="playing")return;}g.round++;g.phase="investigation";g.currentIndex=(g.leadIndex+1)%g.investigators.length;g.leadIndex=g.currentIndex;for(const i of g.investigators){i.actions=i.defeated?0:3;i.ended=!!i.defeated;i.abilityReady=true;i.firstInvestigate=true;i.firstFight=true;}while(g.investigators[g.currentIndex]?.defeated)g.currentIndex=(g.currentIndex+1)%g.investigators.length;emit(g,"round",`第${g.round}轮调查开始`,`${g.investigators[g.currentIndex].playerName}率先行动。`);}
function advanceAct(g){const total=g.investigators.reduce((n,i)=>n+i.clues,0);if(total<g.actClues)return;let need=g.actClues;for(const i of g.investigators){const use=Math.min(i.clues,need);i.clues-=use;need-=use;}g.act++;if(g.act>3)return finish(g,true,"仪式图被撕毁，黑荆宅邸在黎明前恢复沉寂。");g.actClues=[0,2,3,4][g.act]*g.investigators.length;Object.values(g.locations).filter(x=>x.lockedAct===g.act).forEach(x=>x.revealed=true);emit(g,"act",`场景推进至第${g.act}幕`,g.act===2?"家族档案指向宅邸深处。":"最后的线索藏在无窗塔楼。");}
function showToken(t){return typeof t==="number"?(t>=0?`+${t}`:`${t}`):t==="skull"?"骷髅":t==="cultist"?"异教徒":"触手";}
function finish(g,won,text){g.status="finished";g.outcome=won?"won":"lost";g.phase="result";emit(g,won?"resolution":"doom",won?"结局：黎明之前":"结局：无人归来",text);}
function publicRoom(room,id){const base={code:room.code,hostId:room.hostId,players:room.players.map(({token,...p})=>p),settings:room.settings,game:null};if(!room.game)return base;const game=clone(room.game);for(const i of game.investigators){i.handCount=i.hand.length;i.deckCount=i.deck.length;if(i.playerId!==id)i.hand=[];}game.you=game.investigators.find(x=>x.playerId===id);return {...base,game};}
module.exports={defaults,configure,createGame,move,investigate,fight,evade,basic,play,ability,endTurn,publicRoom,advanceAct,mythos,INVESTIGATORS,LOCATIONS};
